package reporter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/mift-enterprise/recon/internal/correlator"
)

type Report struct {
	Target   string                       `json:"target"`
	ScanDate string                       `json:"scan_date"`
	Summary  map[string]int               `json:"summary"`
	Findings []correlator.CorrelatedFinding `json:"findings"`
}

func Generate(findings []correlator.CorrelatedFinding, target string) *Report {
	summary := map[string]int{"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
	for _, f := range findings {
		switch f.Priority {
		case 1:
			summary["critical"]++
		case 2:
			summary["high"]++
		case 3:
			summary["medium"]++
		case 4:
			summary["low"]++
		default:
			summary["info"]++
		}
	}

	return &Report{
		Target:   target,
		ScanDate: time.Now().Format(time.RFC3339),
		Summary:  summary,
		Findings: findings,
	}
}

func Save(report *Report, target string) error {
	outDir := fmt.Sprintf("output/%s-%s", target, time.Now().Format("20060102-150405"))
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	// JSON
	jsonPath := filepath.Join(outDir, "findings.json")
	// TODO: write JSON

	// Markdown (H1/Bugcrowd format)
	mdPath := filepath.Join(outDir, "report.md")
	md := generateMarkdown(report)
	if err := os.WriteFile(mdPath, []byte(md), 0644); err != nil {
		return err
	}

	// PoC files
	pocDir := filepath.Join(outDir, "poc")
	os.MkdirAll(pocDir, 0755)
	for i, f := range report.Findings {
		if f.PoC != "" {
			pocPath := filepath.Join(pocDir, fmt.Sprintf("%03d_%s.md", i+1, sanitize(f.Template)))
			os.WriteFile(pocPath, []byte(f.PoC), 0644)
		}
	}

	fmt.Printf("[REPORT] Output: %s\n", outDir)
	return nil
}

func generateMarkdown(r *Report) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# RECON Scan Report: %s\n\n", r.Target))
	sb.WriteString(fmt.Sprintf("**Scan Date:** %s  \n", r.ScanDate))
	sb.WriteString(fmt.Sprintf("**Total Findings:** %d  \n\n", len(r.Findings)))

	sb.WriteString("## Summary\n\n")
	sb.WriteString("| Severity | Count |\n|---|---|\n")
	for _, sev := range []string{"critical", "high", "medium", "low", "info"} {
		sb.WriteString(fmt.Sprintf("| %s | %d |\n", strings.Title(sev), r.Summary[sev]))
	}
	sb.WriteString("\n")

	sb.WriteString("## Findings\n\n")
	for i, f := range r.Findings {
		sev := priorityToSeverity(f.Priority)
		sb.WriteString(fmt.Sprintf("### %d. [%s] %s\n\n", i+1, strings.ToUpper(sev), f.Template))
		sb.WriteString(fmt.Sprintf("**Host:** %s  \n", f.Host))
		sb.WriteString(fmt.Sprintf("**Type:** %s  \n", f.Type))
		sb.WriteString(fmt.Sprintf("**Confidence:** %.0f%%  \n", f.Confidence*100))
		sb.WriteString(fmt.Sprintf("**Priority:** P%d  \n\n", f.Priority))

		sb.WriteString("**Description:**\n")
		sb.WriteString(fmt.Sprintf("%s\n\n", f.Impact))

		sb.WriteString("**PoC:**\n")
		sb.WriteString(fmt.Sprintf("```bash\n%s\n```\n\n", f.PoC))

		sb.WriteString("**Remediation:**\n")
		sb.WriteString(fmt.Sprintf("%s\n\n", f.Remediation))

		sb.WriteString("---\n\n")
	}

	sb.WriteString("---\n*Generated by RECON - Rapid Exploit Confirmation & Offensive Recon*\n")
	return sb.String()
}

func priorityToSeverity(p int) string {
	switch p {
	case 1:
		return "critical"
	case 2:
		return "high"
	case 3:
		return "medium"
	case 4:
		return "low"
	default:
		return "info"
	}
}

func sanitize(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "/", "-"), " ", "_")
}